### ISSUE TITLE
production code for 1.10.0

### ISSUE THREAD

**Issue by kevinlisota** [voceconnect/lift-search#85]
You have version 1.9.10 on the WordPress repository, but in GitHub, you've updated the version to 1.10.0, which appears to support the 2013-01-01 API for new users. (which is what I need)

Two questions. Can you put a WP-ready version up on the plugins site to match what is in GitHub?

I tried to use the current GitHub master, but I need some pointers on how to build the .js and .css files from your source. Neither are present and the plugin chokes at displaying any admin information without them.

**Comment by prettyboymp** [comment]
1.10.0 isn't production ready, which is why it wasn't yet released to WP.org.  There was some mis-communication that caused the code for 1.10.0 to be tagged as a build when it wasn't yet ready.  It doesn't fully support the 2013-01-01 API.  For now, the only option is to first create an older API instance through the console.

**Comment by kevinlisota** [comment]
Thanks for the clarification. I must be missing something, but I've never been able to create an older API instance in AWS. Perhaps it is because I hadn't used the service until the new API came out. If you have any secrets on how to force the old API, I'd love to hear them.

**Comment by prettyboymp** [comment]
When creating a new domain through the AWS Dashboard, you should have an
option to select the API version.

On Thu, Jan 29, 2015 at 11:24 AM, Kevin Lisota <notifications@github.com>
wrote:

> Thanks for the clarification. I must be missing something, but I've never
> been able to create an older API instance in AWS. Perhaps it is because I
> hadn't used the service until the new API came out. If you have any secrets
> on how to force the old API, I'd love to hear them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voceconnect/lift-search/issues/85#issuecomment-72054425>
> .
>



-- 
Michael Pretty
VP Platforms Architecture
mpretty@voceconnect.com
863.370.3525
Voce Communications, a Porter Novelli Company

**Comment by kevinlisota** [comment]
Actually only true if you had created a CloudSearch domain prior to the launch of the 2013-01-01 API. Here's the sentence from their docs: "If you created Amazon CloudSearch domains prior to the launch of the 2013-01-01 API, you can choose which API version to use when you create a new domain."

Chances are that you've never come across it because you had been creating CloudSearch domains previously.

**Comment by prettyboymp** [comment]
I did not realize that.  Thank you for the clarification.

On Thu, Jan 29, 2015 at 2:33 PM, Kevin Lisota <notifications@github.com>
wrote:

> Actually only true if you had created a CloudSearch domain prior to the
> launch of the 2013-01-01 API. Here's the sentence from their docs: "If you
> created Amazon CloudSearch domains prior to the launch of the 2013-01-01
> API, you can choose which API version to use when you create a new domain."
>
> Chances are that you've never come across it because you had been creating
> CloudSearch domains previously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voceconnect/lift-search/issues/85#issuecomment-72088720>
> .
>



-- 
Michael Pretty
VP Platforms Architecture
mpretty@voceconnect.com
863.370.3525
Voce Communications, a Porter Novelli Company
